# --- SITE SETTINGS ---

title: "Benoit Wery"
email: null
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  benwe95


# --- BUILD SETTINGS ---

# kramdown is a parser that converts Markdown syntax into HTML 
# ("Kramdown extends Markdown with some useful features, like adding classes and IDs to elements without 
# having to resort to the HTML syntax.  ex: # My Header {#md-id} ")
markdown: kramdown

# theme should be set either to a specific value or to null.
# Otherwise 'github-pages' gem will automatically generate a default stylesheet which is no necessary.
theme: null

# This will force Jekyll to include the following folders in the destination folder (_site)
# even if they begin with . _ # or ~
include: [_pages]

collections:
  projects:
    output: true
    order:
      - kapu.md
      - simulation-reseaux.md
      - notepad.md
      - timelines.md
      - website.md
  recommandations:
    output: true

# These are default values attached to particular type of files
defaults:
  - scope:
      path: _projects
    values:
      layout: project
  - scope:
      path: _recommandations
    values:
      layout: recommandation
  - scope: 
      path: ""
    values:
      layout: default

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
