version: "3"

services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: jekyll-3.8-serve-personalwebsite
    command: jekyll serve --watch --force_polling
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
