version: "3"

services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: jekyll-serve
    command: jekyll serve --watch --force_polling
    volumes:
      - ./src/:/srv/jekyll
    ports:
      - "4000:4000"
